export const tokens = {
  colors: {
    background: "#0b1326",
    onBackground: "#dae2fd",
    surface: "#0b1326",
    onSurface: "#dae2fd",
    surfaceVariant: "#2d3449",
    onSurfaceVariant: "#d5c3be",
    primary: "#eebbad",
    onPrimary: "#48281f",
    primaryContainer: "#b88a7d",
    onPrimaryContainer: "#44251c",
    secondary: "#bcc7de",
    onSecondary: "#263143",
    secondaryContainer: "#3e495d",
    onSecondaryContainer: "#aeb9d0",
    tertiary: "#c3c3e8",
    onTertiary: "#2c2e4b",
    tertiaryContainer: "#9192b5",
    onTertiaryContainer: "#292b48",
    outline: "#9d8d89",
    outlineVariant: "#514441",
    error: "#ffb4ab",
    onError: "#690005",
  },
  typography: {
    displayLg: {
      fontFamily: "Hanken Grotesk",
      fontSize: "48px",
      fontWeight: "700",
      lineHeight: "56px",
      letterSpacing: "-0.02em",
    },
    headlineLg: {
      fontFamily: "Hanken Grotesk",
      fontSize: "32px",
      fontWeight: "600",
      lineHeight: "40px",
    },
    headlineLgMobile: {
      fontFamily: "Hanken Grotesk",
      fontSize: "28px",
      fontWeight: "600",
      lineHeight: "36px",
    },
    titleMd: {
      fontFamily: "Hanken Grotesk",
      fontSize: "20px",
      fontWeight: "600",
      lineHeight: "28px",
    },
    bodyLg: {
      fontFamily: "Inter",
      fontSize: "18px",
      fontWeight: "400",
      lineHeight: "28px",
    },
    bodyMd: {
      fontFamily: "Inter",
      fontSize: "16px",
      fontWeight: "400",
      lineHeight: "24px",
    },
    labelSm: {
      fontFamily: "Inter",
      fontSize: "12px",
      fontWeight: "600",
      lineHeight: "16px",
      letterSpacing: "0.05em",
    },
  },
  spacing: {
    base: "8px",
    marginMobile: "20px",
    marginDesktop: "40px",
    gutter: "16px",
    containerMax: "1200px",
  },
  roundness: {
    sm: "4px",
    DEFAULT: "8px",
    md: "12px",
    lg: "16px",
    xl: "24px",
    full: "9999px",
  },
};
